openapi: 3.0.1
info:
  title: Operation API
  version: 1.0.0
  description: API для управления операциями с хранилищем
servers:
  - url: /api/v1/operations
paths:
  /:
    get:
      summary: Получить содержимое хранилища
      parameters:
        - name: table
          in: path
          required: true
          schema:
            type: string
          description: Название таблицы
      responses:
        '200':
          description: Успешное получение содержимого
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string

  /key/{key}:
    get:
      summary: Получить значение по ключу
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Ключ значения
        - name: required
          in: query
          required: false
          schema:
            type: boolean
          description: Требовать ли точное совпадение ключа
      responses:
        '200':
          description: Значение успешно получено
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Значение не найдено

    put:
      summary: Обновить значение по ключу
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Ключ значения
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: string
      responses:
        '200':
          description: Значение успешно обновлено
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Значение не найдено

    delete:
      summary: Удалить значение по ключу
      parameters:
        - name: key
          in: path
          required: true
          schema:
            type: string
          description: Ключ значения
      responses:
        '200':
          description: Значение успешно удалено
          content:
            application/json:
              schema:
                type: string
        '404':
          description: Значение не найдено

  /clear:
    delete:
      summary: Очистить хранилище
      responses:
        '200':
          description: Таблица успешно очищена
          content:
            application/json:
              schema:
                type: string